"""Add a blogs table

Revision ID: 119918dc8efa
Revises: e2412789c190
Create Date: 2024-04-10 21:26:25.235761

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "119918dc8efa"
down_revision = "e2412789c190"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogs",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            primary_key=True,
            comment="This column stores autoincrement id",
        ),
        sa.Column(
            "author_id",
            sa.Integer(),
            nullable=False,
            comment="This column stores author id of the blog",
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "summary",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "content",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
    )
    op.create_index(
        index_name=op.f("ix_created_at"),
        table_name="blogs",
        columns=[
            "created_at",
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(index_name=op.f("ix_created_at"), table_name="blogs")
    op.drop_table("blogs")
    # ### end Alembic commands ###
